# Generated by Django 6.0.2 on 2026-03-18 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_document_file_doc_studentprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='name',
            field=models.CharField(choices=[('1AP', '1ere annee'), ('2ST', '2eme annee (ST)'), ('2MI', '2eme annee (MI)'), ('3ST', '3eme annee (ST)'), ('3MI', '3eme annee (MI)')], max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='year',
            field=models.CharField(blank=True, choices=[('1AP', '1ere annee'), ('2ST', '2eme annee (ST)'), ('2MI', '2eme annee (MI)'), ('3ST', '3eme annee (ST)'), ('3MI', '3eme annee (MI)')], max_length=10),
        ),
    ]
