# Generated by Django 6.0.2 on 2026-03-28 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_favori'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indexed_at', models.DateTimeField(auto_now_add=True)),
                ('chunk_count', models.IntegerField(default=0)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='index', to='core.document')),
            ],
        ),
    ]
